name: CI - Python Tests

on:
    pull_request:
        branches:
        - main
        paths:
        - '**/*.py'
        - '.github/workflows/**'

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  tests:
    name: Build & Test
    runs-on: windows-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov
          pip install pylint
      - name: Run tests with coverage
        run: |
          python -m pytest test_excel_to_sql_converter.py -v
      - name: Run pylint
        run: |
          pylint excel_to_sql_converter.py --output-format=parseable > pylint-report.txt || true
      - name: Upload coverage & pylint reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            pylint-report.txt

  build-linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          python -m pytest test_excel_to_sql_converter.py -v
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-linux
          path: |
            .